# Make a copy of this file, rename it to discord-uptime.toml, then make edits in your newly copied file to configure your bot.

discordGuildId = "your-guild-id-here"
discordToken = "your-bot-token-here"

[discordUsers.my-bot]
userId = "some-discord-user-id"

[discordUsers.my-other-bot]
userId = "some-other-discord-user-id"
statusToHttpResponseCodeMap = {
    online = 502,
    idle = 502,
    dnd = 502,
    offline = 200
}